name: Run Typesense DocSearch Scraper
description: Crawl and index your documentation site for Typesense DocSearch

branding:
  icon: search
  color: black

inputs:
    config:
        description: The path to your DocSearch config JSON file, relative to the root of your repository. Defaults to "docsearch.config.json".
        required: false
        default: docsearch.config.json

secrets:
    dotenv-file:
        description: Dotenv file contaiment
        required: false

runs:
  using: composite
  steps:
    - name: Create env file
      run: |
        echo "${{ secrets.dotenv-file }}" > .env

    - name: Run DocSearch Scraper
      shell: bash
      run: |
        docker run \
          --env-file .env \
          -e CONFIG="$(cat ${{ inputs.config }} | jq -r tostring)" \
          typesense/docsearch-scraper
